min_version = "2026.2.4"

[env]
_.python.venv = { path = ".venv", create = true }

[tools]
python = "3.12"
uv = "latest"
ruff = "latest"

[tasks.setup]
description = "Install dependencies and local package in editable mode with dev components"
run = "uv sync"

[tasks.lint]
description = "Lint the code"
run = "ruff check src/"

[tasks."run:sssd-inspector"]
description = "Execute sssd-inspector instantly using local source code"
run = "uv run sssd-inspector"

[tasks."run:supportconfig2sssd-logs"]
description = "Execute supportconfig2sssd-logs instantly using local source code"
run = "uv run supportconfig2sssd-logs"

[tasks.typecheck]
description = "Verify type compliance using pyright"
run = "uv run pyright src/"

[tasks.test]
description = "Run tests"
run = "uv run pytest"

[tasks."install-global"]
description = "Install the finished application locally into an isolated path"
run = "uv tool install . --force"